import * as React from "react"
import type { ColumnDef } from "@tanstack/react-table"
import { FileText, IndianRupee, Percent } from "lucide-react"
import { PageHeader } from "@/components/shared/page-header"
import { StatCard } from "@/components/shared/stat-card"
import { DataTable } from "@/components/shared/data-table"
import { DateRangeFilter, type DateRange } from "@/components/shared/date-range-filter"
import { ErrorState } from "@/components/shared/error-state"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { useApiQuery } from "@/hooks/use-api"
import { api } from "@/lib/api"
import type { TDSReport } from "@/lib/api-types"
import { exportToCsv } from "@/lib/utils"
import { formatCount, formatMoney, toNumberOrZero } from "@/lib/money"

type TdsRow = TDSReport["rows"][number]

/** Renders "2026-07" as "July 2026". */
function monthLabel(month: string): string {
  const [year, m] = month.split("-")
  const index = Number(m) - 1
  if (!year || Number.isNaN(index)) return month
  const name = new Date(2000, index, 1).toLocaleString("en-IN", { month: "long" })
  return `${name} ${year}`
}

const columns: ColumnDef<TdsRow>[] = [
  {
    accessorKey: "month",
    header: "Month",
    cell: ({ row }) => <span className="text-sm font-medium text-gray-900">{monthLabel(row.original.month)}</span>,
  },
  {
    accessorKey: "count",
    header: "Transactions",
    cell: ({ row }) => <span className="table-num text-sm text-gray-700">{formatCount(row.original.count)}</span>,
  },
  {
    accessorKey: "commission",
    header: "Gross Commission",
    cell: ({ row }) => <span className="table-num text-sm text-gray-700">{formatMoney(row.original.commission)}</span>,
  },
  {
    accessorKey: "tds",
    header: "TDS Deducted",
    cell: ({ row }) => (
      <span className="table-num text-sm font-medium text-danger-600">{formatMoney(row.original.tds)}</span>
    ),
  },
  {
    id: "net",
    header: "Net Commission",
    cell: ({ row }) => {
      // Commission minus TDS only. GST is deducted separately and appears on the
      // GST report, so this is not the retailer's final take-home.
      const net = toNumberOrZero(row.original.commission) - toNumberOrZero(row.original.tds)
      return <span className="table-num text-sm font-semibold text-gray-900">{formatMoney(net)}</span>
    },
  },
]

export function TdsReportPage() {
  const [range, setRange] = React.useState<DateRange>({})

  const query = useApiQuery(() => api.reports.tds(range), [range.from, range.to])
  const report = query.data

  const rows = report?.rows ?? []
  const totalCommission = rows.reduce((sum, r) => sum + toNumberOrZero(r.commission), 0)
  const totalTds = toNumberOrZero(report?.totalTds)

  // The effective rate is only meaningful when there is commission to rate.
  const effectiveRate = totalCommission > 0 ? (totalTds / totalCommission) * 100 : null

  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="TDS Report"
        description="TDS deducted from your commission earnings"
        actions={<DateRangeFilter value={range} onChange={setRange} />}
      />

      {query.error ? (
        <ErrorState description={query.error} onRetry={query.refetch} />
      ) : (
        <>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
            <StatCard
              label="Total TDS Deducted"
              value={formatMoney(report?.totalTds ?? "0")}
              icon={IndianRupee}
              iconClassName="bg-danger-50 text-danger-600"
              loading={query.loading}
            />
            <StatCard
              label="Gross Commission"
              value={formatMoney(totalCommission)}
              icon={FileText}
              iconClassName="bg-brand-50 text-brand-600"
              loading={query.loading}
            />
            <StatCard
              label="Effective TDS Rate"
              value={effectiveRate === null ? "—" : `${effectiveRate.toFixed(2)}%`}
              icon={Percent}
              iconClassName="bg-info-bg text-info"
              loading={query.loading}
            />
          </div>

          <Card>
            <CardHeader>
              <CardTitle>Tax Details</CardTitle>
              <CardDescription>
                {report?.pan ? `PAN ${report.pan}` : "No PAN on file. Add it in your profile so it appears on this report."}
                {report?.financialYear ? ` · Financial year ${report.financialYear}` : ""}
              </CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-xs text-gray-500">
                TDS is withheld from the commission a transaction earns. Form 16A certificates are issued by the
                deductor's quarterly TDS filing and are not generated by this platform &mdash; use these figures to
                reconcile against the certificate you receive.
              </p>
            </CardContent>
          </Card>

          <DataTable
            columns={columns}
            data={rows}
            loading={query.loading}
            onExport={() =>
              exportToCsv(
                "tds-report",
                rows.map((r) => ({
                  month: monthLabel(r.month),
                  transactions: r.count,
                  grossCommission: toNumberOrZero(r.commission),
                  tds: toNumberOrZero(r.tds),
                  netCommission: toNumberOrZero(r.commission) - toNumberOrZero(r.tds),
                })),
              )
            }
            emptyTitle="No TDS recorded for this period"
            emptyDescription="TDS appears here once you have settled transactions that earned commission"
          />
        </>
      )}
    </div>
  )
}
