FROM node:22-alpine

RUN addgroup -g 1001 -S nodejs && adduser -S -u 1001 -G nodejs nextjs

WORKDIR /app

# Copy prebuilt standalone output
COPY --chown=nextjs:nodejs dist-prebuilt .

USER nextjs

EXPOSE 3000

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
